name: Security Scan
on:
  push:
    branches: [master, dev]
jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Scan image
        uses: anchore/scan-action@master
        with:
          image-reference: "localbuild/testimage:latest"
          dockerfile-path: "./Dockerfile"

      - name: anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
